export const GET_ALL_CHAMPIONS_REQUEST = 'GET_ALL_CHAMPIONS';
export const GET_ALL_CHAMPIONS_SUCCESS = 'GET_ALL_CHAMPIONS_SUCCESS';
export const GET_ALL_CHAMPIONS_FAIL = 'GET_ALL_CHAMPIONS_FAIL';

export const GET_CHAMPION_BY_ID_REQUEST = 'GET_CHAMPION_BY_ID_REQUEST';
export const GET_CHAMPION_BY_ID_SUCCESS = 'GET_CHAMPION_BY_ID_SUCCESS';
export const GET_CHAMPION_BY_ID_FAIL = 'GET_CHAMPION_BY_ID_FAIL';
// GET_ALL_CHAMPIONS, GET_CHAMPION_BY_ID
